### ISSUE TITLE
func b c 

### ISSUE THREAD

**Issue by TJJTJJTJJ** [human-analysis/intrinsic-dimensionality#1]
https://github.com/human-analysis/intrinsic-dimensionality/blob/30efbeafac585fa59ababc06c9c79bbf387bec7a/ID_estimate/ID_graph_largedata.py#L22

Hello, in your func, b and c doesn't mean anything, but in #L286

```python
y2=func(left_distr_x,fit[0][0],fit[0][1],fit[0][2])
```
I think is there some missing?

Best wishes,

**Comment by gongsixue** [comment]
Hi,

func is the logarithm distribution of the geodesic distance of D-hypersphere. Only 'a' in func is the valid coefficient and represents the dimensionality of the D-hypersphere. 'b' and 'c' are obsolete. I forgot to remove them from func. Sorry for the confusion.

In the curve fitting results, fit[0][0] is 'a' in func, and is the fitted intrinsic dimensionality.
