### ISSUE TITLE
Gaussian Fitting to determine ratio R

### ISSUE THREAD

**Issue by TJJTJJTJJ** [human-analysis/intrinsic-dimensionality#2]
Hi:
in your paper, it should be $y=log(\frac{p(r)}{p(r_{max})})$, but in your code, in my opinion, (4*a*c-b**2)/4./a is to fit $p(r_{max})$, so the code should be :

```
left_distr_y= np.log(distr_y[np.logical_and(np.logical_and(distr_x[:]>rmin,distr_x[:]<=rM),distr_y[:]>0.000001)])-np.log((4*a*c-b**2)/4./a)
```

https://github.com/human-analysis/intrinsic-dimensionality/blob/30efbeafac585fa59ababc06c9c79bbf387bec7a/ID_estimate/ID_graph_largedata.py#L273-L274

Or just I make a confuse?

_______
And fuc2 is to fit which function? (5)?
```
    fit = curve_fit(func2,left_distr_x,left_distr_y)
    ratio=np.sqrt(fit[0][0])
```

And the ratio is to refer d? or is there anything I make a mistake?

Thank you!
Best Wishes!

**Comment by vboddeti** [comment]
(4ac-b**2)/4./a is after taking the log of the denominator. $p(r_{max})$ itself contains exp(xxx), so after taking the log of the denominator the expression becomes simpler.
