### ISSUE TITLE
Equation 4 and code

### ISSUE THREAD

**Issue by TJJTJJTJJ** [human-analysis/intrinsic-dimensionality#3]
Hi:
I have another problem about equation 4 and code.
$$d_H(x_i,x_j)-d_L(y_i, y_j)$$
in my opinion, $d_H$ is to use geodesic distance, and $d_L$ is to use Euclidean or cosine distance.

but in your code, 

```
        if y1 is not None:
            if self.dist_metric == 'cosine':
                dist_in = torch.sum(torch.mul(x1,x2) / (torch.norm(x1,dim=1,keepdim=True)
                    *torch.norm(x2,dim=1,keepdim=True)), dim=1)
                dist_out = torch.sum(torch.mul(y1,y2) / (torch.norm(y1,dim=1,keepdim=True)
                    *torch.norm(y2,dim=1,keepdim=True)), dim=1)
            elif self.dist_metric == 'Euclidean':
                dist_in = torch.norm(x1-x2, dim=1, keepdim=True)
                dist_out = torch.norm(y1-y2, dim=1, keepdim=True)
            else:
                raise(RuntimeError('Metric does not support!'))
```
So, in your paper, it is that $d_H$ and $d_L$ both use Euclidean, so is there any problem?

**Comment by vboddeti** [comment]
You are right,  $d_H$ should ideally be geodesic distance. Geodesic distance is expensive to compute at scale on the fly, so you will have to pre-compute, cache and use it for training. For the face experiment we observed that using Euclidean did not degrade our results significantly, in terms of performance. So we traded-off a slight performance drop for computational efficiency.
