### ISSUE TITLE
Table 2 dose not meet my reproduce.

### ISSUE THREAD

**Issue by TJJTJJTJJ** [human-analysis/intrinsic-dimensionality#4]
How do you get the feature of LFW? In your table 2, 512-dim only achieve 96.74\%, but when I look at the implement of [sphereface](https://github.com/wy1iu/sphereface), it could achieve 99.30\%. And when I test the LFW feature the sphereface released, it could achieve 98.02\%, and, when I use PCA to reduce the dimension to 16, it still achieve 0.8481, which is higher than your reported 32.67\%.  

So I have a question: where does your feature come from? Could you give me your lfw feature? I want to reproduce the table 2.

**Comment by vboddeti** [comment]
The result of 99.30% on LFW with Sphereface is probably from the standard LFW evaluation protocol. In our paper we instead follow the BLUFR evaluation protocol on LFW. On the BLUFR protocol Sphereface achieves 96.74% only.
