### ISSUE TITLE
What is meant by Genuine and imposter feature representation?

### ISSUE THREAD

**Issue by amajee11us** [human-analysis/intrinsic-dimensionality#5]
There is no mention in the paper about the genuine and imposter feature representations.
Also, the algorithm of DeepMDS is supposedly unsupervised so what are the labels being used for?

**Comment by vboddeti** [comment]
The algorithm is unsupervised in the general case. 

In our application, which was face verification, there is a large imbalance between genuine and imposter pair of samples. So to make the training faster, in each mini batch we balance the number of genuine and imposter pairs.

In your application if you do not have any additional information you can just try to train on all possible pairs without worrying about balancing the mini batches.
