### ISSUE TITLE
DeepMDS not giving correct accuracy on VOC

### ISSUE THREAD

**Issue by AmeetR** [human-analysis/intrinsic-dimensionality#6]
Hi,

I'm trying to use DeepMDS on VOC for a self supervised learning task, however it's going down by a lot from the baseline when we even try to do 9600 -- 8192, see 50% drop, I'm not sure why this would happen. As you guys proved, there was nearly all information retention at intrinsic space, so I'm a bit confused.

**Comment by vboddeti** [comment]
The intrinsic dimension only alludes to the existence of a low-dimensional space that can retain all the information. It does not guarantee that one can find such a low-dimensional space efficiently. DeepMDS attempts to find "a" low-dimensional space. The quality of the solution depends on the how well you can learn the network, which in turn depends on a whole host of hyper-parameters. 

If you can provide more information (a link to a repo with a small sample of data), perhaps we can look into why it is not working as well.
