### ISSUE TITLE
run ID_graph_largedata.py

### ISSUE THREAD

**Issue by zheng547** [human-analysis/intrinsic-dimensionality#7]
Hello,
when I run ID_graph_largedata.py, the console reported,
'''
FileNotFoundError: [Errno 2] No such file or directory: '/research/prip-gongsixu/results/feats/evaluation/feat_lfwblufr_sphere.mat',
'''
I think the mat document is needed, or how to solve the problem?

**Comment by vboddeti** [comment]
The mat file contains the extracted features for your dataset. We will not be able to provide it, you need to change that path with your own features.
